Mcneude\PortfolioBundle\Entity\Contact:
    type: entity
    table: contact
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        accrocheForm:
            type: text
            nullable: true
            column: accroche_form
        accrocheReseaux:
            type: text
            nullable: true
            column: accroche_reseaux
    lifecycleCallbacks: {  }
