Mcneude\PortfolioBundle\Entity\ContactReseaux:
    type: entity
    table: contact_reseaux
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nom:
            type: string
            length: 100
            fixed: false
            nullable: true
        classReseau:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: class_reseau
        description:
            type: text
            nullable: true
        urlImage:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: url_image
        url:
            type: string
            length: 200
            fixed: false
            nullable: true
        position:
            type: integer
            unsigned: false
            nullable: true
    lifecycleCallbacks: {  }
