Mcneude\PortfolioBundle\Entity\Etude:
    type: entity
    table: etude
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nom:
            type: string
            length: 45
            fixed: false
            nullable: true
        description:
            type: string
            length: 200
            fixed: false
            nullable: true
        urlVisuel:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: url_visuel
    lifecycleCallbacks: {  }
