Mcneude\PortfolioBundle\Entity\FosUser:
    type: entity
    table: fos_user
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
