Mcneude\PortfolioBundle\Entity\Home:
    type: entity
    table: home
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        titre:
            type: string
            length: 45
            fixed: false
            nullable: true
        accroche:
            type: text
            nullable: true
        urlImage:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: url_image
        apprendre:
            type: text
            nullable: true
        construire:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
