Mcneude\PortfolioBundle\Entity\ParcoursAccroches:
    type: entity
    table: parcours_accroches
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        accrocheEtudes:
            type: text
            nullable: true
            column: accroche_etudes
        accrocheExperiences:
            type: text
            nullable: true
            column: accroche_experiences
        accrocheExperiencesComplementaires:
            type: text
            nullable: true
            column: accroche_experiences_complementaires
        accrocheInterets:
            type: text
            nullable: true
            column: accroche_interets
    lifecycleCallbacks: {  }
