Mcneude\PortfolioBundle\Entity\Parcours:
    type: entity
    table: parcours
    gedmo:
        translation:
            locale: locale
            entity: Mcneude\PortfolioBundle\Entity\ParcoursTranslation

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        experiencesComplementaires:
            type: text
            nullable: true
            column: experiences_complementaires
            gedmo:
              - translatable

        interets:
            type: text
            nullable: true
            gedmo:
              - translatable

    oneToMany:
        translations:
            targetEntity: ParcoursTranslation
            cascade: ["persist", "remove"]
            mappedBy: object

    lifecycleCallbacks: {  }
