Mcneude\PortfolioBundle\Entity\ParcoursEtudesTranslation:
    type: entity
    table: parcours_etudes_translation
    uniqueConstraints:
        lookup_unique_idx:
            columns: [locale,object_id,field]
    id:
      id:
        type: integer
        generator:
          strategy: AUTO

    fields:
        locale:
            type: string
            length: 8
        field:
            type: string
            length: 32
        content:
            type: text
            nullable: true
    manyToOne:
        object:
            targetEntity: ParcoursEtudes
            cascade: {  }
            mappedBy: null
            inversedBy: translations
            joinColumns:
                object_id:
                  referencedColumnName: id
    lifecycleCallbacks: {  }
