Mcneude\PortfolioBundle\Entity\Projets:
    type: entity
    table: projets
    gedmo:
        translation:
            locale: locale
            entity: Mcneude\PortfolioBundle\Entity\ProjetsTranslation


    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nom:
            type: string
            length: 45
            fixed: false
            nullable: true
            gedmo:
              - translatable
        position:
            type: integer
            unsigned: false
            nullable: true
        description:
            type: text
            nullable: true
            gedmo:
              - translatable

        difficultes:
            type: text
            nullable: true
            gedmo:
              - translatable

        technologies:
            type: text
            nullable: true
            gedmo:
              - translatable

        competencesAcquises:
            type: text
            nullable: true
            column: competences_acquises
            gedmo:
              - translatable

        urlMiniature:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: url_miniature

        slug:
            type: string
            length: 45
            fixed: false
            nullable: false

        urlExternal:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: url_external

        isWebsite:
            type: boolean
            nullable: true
            column: is_website

    manyToMany:
        projetsGroupe:
            targetEntity: ProjetsGroupes
            cascade: {  }
            mappedBy: null
            inversedBy: projets
            joinTable:
                name: groupes_has_projets
                joinColumns:
                    -
                        name: projets_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: projets_groupe_id
                        referencedColumnName: id
            orderBy: null

    oneToMany:
        translations:
            targetEntity: QuisuisjeTranslation
            cascade: ["persist", "remove"]
            mappedBy: object

    lifecycleCallbacks: {  }
