Mcneude\PortfolioBundle\Entity\Projets:
    type: entity
    table: projets
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nom:
            type: string
            length: 45
            fixed: false
            nullable: true
        position:
            type: integer
            unsigned: false
            nullable: true
        description:
            type: text
            nullable: true
        difficultes:
            type: text
            nullable: true
        technologies:
            type: text
            nullable: true
        competencesAcquises:
            type: text
            nullable: true
            column: competences_acquises
        urlMiniature:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: url_miniature
        urlInternal:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: url_internal
        urlExternal:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: url_external
        isWebsite:
            type: boolean
            nullable: true
            column: is_website
    lifecycleCallbacks: {  }
