Mcneude\PortfolioBundle\Entity\ProjetsTranslation:
    type: entity
    table: projets_translation
    uniqueConstraints:
        lookup_unique_idx:
            columns: [locale,object_id,field]
    id:
      id:
        type: integer
        generator:
          strategy: AUTO

    fields:
      locale:
          type: string
          length: 8
      field:
          type: string
          length: 32
      content:
          type: text
          nullable: true
    manyToOne:
      object:
          targetEntity: ProjetsTranslation
          cascade: {  }
          mappedBy: null
          inversedBy: translations
          joinColumns:
            object_id:
              referencedColumnName: id
    lifecycleCallbacks: {  }
