Mcneude\PortfolioBundle\Entity\ProjetImages:
    type: entity
    table: projet_images
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        url:
            type: string
            length: 45
            fixed: false
            nullable: true
        nom:
            type: string
            length: 200
            fixed: false
            nullable: true
        position:
            type: integer
            unsigned: false
            nullable: true
    manyToOne:
        projet:
            targetEntity: Projets
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                projet_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
