Mcneude\PortfolioBundle\Entity\Quisuisje:
    type: entity
    table: quisuisje
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        pourquoi:
            type: text
            nullable: true
        competencesTech:
            type: text
            nullable: true
            column: competences_tech
        competencesCom:
            type: text
            nullable: true
            column: competences_com
        methodes:
            type: text
            nullable: true
        politique:
            type: text
            nullable: true
        infos:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
