Mcneude\PortfolioBundle\Entity\QuisuisjeCompetences:
    type: entity
    table: quisuisje_competences
    gedmo:
        translation:
            locale: locale
            entity: Mcneude\PortfolioBundle\Entity\QuisuisjeCompetencesTranslation
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nom:
            type: string
            length: 45
            fixed: false
            nullable: true
            gedmo:
              - translatable
        description:
            type: text
            nullable: true
            gedmo:
              - translatable
        position:
            type: integer
            unsigned: false
            nullable: true
        urlImage:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: url_image
        isCompetencesTechniques:
            type: boolean
            nullable: true
            column: is_competences_techniques
    oneToMany:
        translations:
            targetEntity: QuisuisjeCompetencesTranslation
            cascade: ["persist", "remove"]
            mappedBy: object

    lifecycleCallbacks: {  }
