Mcneude\PortfolioBundle\Entity\Quisuisje:
    type: entity
    table: quisuisje
    gedmo:
        translation:
            locale: locale
            entity: Mcneude\PortfolioBundle\Entity\QuisuisjeTranslation

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        pourquoi:
            type: text
            nullable: true
            gedmo:
              - translatable

        methodes:
            type: text
            nullable: true
            gedmo:
              - translatable

        politique:
            type: text
            nullable: true
            gedmo:
              - translatable

        infos:
            type: text
            nullable: true
            gedmo:
              - translatable
    oneToMany:
        translations:
            targetEntity: QuisuisjeTranslation
            cascade: ["persist", "remove"]
            mappedBy: object

    lifecycleCallbacks: {  }
