Mcneude\PortfolioBundle\Entity\QuisuisjeCompetences:
    type: entity
    table: quisuisje_competences
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nom:
            type: string
            length: 45
            fixed: false
            nullable: true
        description:
            type: text
            nullable: true
        position:
            type: integer
            unsigned: false
            nullable: true
        image:
            type: string
            length: 200
            fixed: false
            nullable: true
        isCompetencesTechniques:
            type: boolean
            nullable: true
            column: is_competences_techniques
    lifecycleCallbacks: {  }
