imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

    # Admin
    - { resource: @PortfolioBundle/Resources/config/admin.yml }

framework:
    #esi:             ~s
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: false
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
   debug: "%kernel.debug%"
   use_controller: false
   filters:
       cssrewrite: ~
       less:
           node: /usr/local/bin/node
           node_paths: [/usr/local/bin/node, /usr/local/lib/node_modules]
       yui_css:
          jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
       yui_js:
          jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

        #Doctrine Extension
        mappings:
          gedmo_translatable:
                type: yml
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false

# StofDoctrineBundle
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            translatable: true

#TranslationFormBundle
a2lix_translation_form:
    locales: %locales%     # [optional] Array of the translation locales (The default locale have to be excluded). Can also be specified in the form builder.

# Template
twig:
    globals:
        languages: [fr, en]
        blog_url: http://www.web-techno.org
    form:
        resources:
            - 'A2lixTranslationFormBundle::form.html.twig'


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Twitter module configuration
endroid_twitter:
    consumer_key: "ZHNaChFSo2UsYcbLJw"
    consumer_secret: "skuARP5rSY0f9Y4qlOzwsNtlo9Uowv9G4J7TYcAcNc"
    access_token: "109274686-FnFFVbIprkT75WtItxhdsr09zWTBw3jcZo2krUrY"
    access_token_secret: "9dOq4JvVmo1bBkntgq7RX3Nke7FzvYpzv3ZySmfWhI"

# Sonata Block Bundle
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

# Admin
sonata_admin:
    title:      Portfolio Matthieu Cneude
    templates:
      layout: PortfolioBundle:Admin:standard_layout.html.twig

# FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class:    Application\Sonata\UserBundle\Entity\User

    group:
        group_class: Application\Sonata\UserBundle\Entity\Group

#TinyMCE for Admin
stfalcon_tinymce:
        include_jquery: true
        tinymce_jquery: true
        theme:
            simple:
                plugins:
                    - "lists"

#JMSi18nRoutingBundle
jms_i18n_routing:
    default_locale: "%locale%"
    locales: %locales%
    strategy: "prefix_except_default"