parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     portfolio
    database_user:     root
    database_password: droder86

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    locales:           [fr, en]
    secret:            token458767485portfolio45

    admin_email:       matthieu.cneude@gmail.com
    admin_email_subject_prefixe: Mail envoyé depuis le portfolio -
    twitter_account: Cneude_Matthieu