# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.post:
        class: Mcneude\PortfolioBundle\Admin\ProjetAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenus", label: "Projets" }
        arguments:
            - ~
            - Mcneude\PortfolioBundle\Entity\Projet
            - ~
        calls:
            - [ setTranslationDomain, [PortfolioBundle]]