parameters:
#    portfolio.example.class: Mcneude\PortfolioBundle\Example

services:
#    portfolio.example:
#        class: %portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
