parameters:
#    portfolio.example.class: Mcneude\PortfolioBundle\Example

services:
# src/Mcneude/PortfolioBundle/Resources/config/services.yml
services:
     portfolio.form.type.Contact:
        class: Mcneude\PortfolioBundle\Formulaire\type\ContactType
        tags:
            - { name: form.type, alias: Contact }
